pollsapp2/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.home, name='home'),
    path('<int:q_id>/vote/', views.vote, name='vote'),
    path('<int:q_id>/results/', views.results, name='results')
]

pollsapp2/pollsapp2/urls.py
from django.contrib import admin
from django.http import HttpResponse
from django.urls import path, include

def hello(request, num):
    html = ''
    for i in range(10):
        html += f"<p>{ i + 1 } * {num} = { (i + 1) * num}</p>"
    return HttpResponse("<h1>Hello!</h1>" + html)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/<int:num>/', hello, name='hello'),
    path('', include('polls.urls'))
]

pollsapp2/polls/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=150)
    pub_date = models.DateTimeField()

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=100)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

pollsapp2/polls/views.py
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render

from .models import Question, Choice

# Create your views here.
def home(request):
    # return HttpResponse("welcome come")
    questions = Question.objects.all()
    return render(request, 'polls/home.html', {
        "questions": questions
    })

def vote(request, q_id):
    question = get_object_or_404(Question, id=q_id)
    question = Question.objects.get(id=q_id)
    if request.method == 'POST':
        try:
            choice = request.POST['choice']
            c = Choice.objects.get(id=choice)
            c.votes += 1
            c.save()
            return redirect('polls:results', q_id)
        except(KeyError):
            return render(request, 'polls/question.html',
                         { "question": question,
                           "error_message": "Debes seleccionar una opcion"  })
    return render(request, 'polls/question.html',
                 { "question": question })

def results(request, q_id):
    try:
        question = Question.objects.get(id=q_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exits")
    
    labels = [c.choice_text for c in question.choice_set.all()]
    data = [c.votes for c in question.choice_set.all()]
    context = {"question": question, "labels": labels, "data": data}
    return render(request, "polls/results.html", context)



    #return render(request, 'polls/results.html',
     #             { "question": question })

pollsapp2/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>Encuestas | {% block title %}{% endblock %}</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    
</body>
</html>

pollsapp2/templates/polls/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<h1>Bienvenido a las Encuestas</h1>
<h1>Responde alguna de las siguientes:</h1>
<ul>
    <h3>Encuestas</h3>
    {% for q in questions %}
    <li>
        <a href="{% url 'polls:vote' q.id %}">{{ q.question_text }}</a>
        <a href="{% url 'polls:results' q.id %}">--Resultados</a>
    </li>
    {% endfor %}
</ul>
{% endblock %}

pollsapp2/templates/polls/question.html
{% extends 'base.html' %}
{% block title %}Vota{% endblock %}
{% block content %}
<h1>{{ question }}</h1>
{% if error_message %}
<div class="alert">
    <p>{{ error_message }}</p>
</div>
{% endif %}
<form method="post">
    {% csrf_token %}
    {% for c in question.choice_set.all %}
    <input 
        type="radio" 
        name="choice" 
        id="choice_{{ c.id }}"
        value="{{ c.id }}">
    <label for="choice_{{ c.id }}">{{ c.choice_text }}</label>
    <br>
    {% endfor %}
    <input type="submit" value="Votar">
</form>
{% endblock %}

pollsapp2/templates/polls/results.html
{% extends 'base.html' %}

{% block title %}Resultado{% endblock %}

{% block content %}
<h1>{{ question }}</h1>
<ul>
    {% for c in question.choice_set.all %}
    <li>{{ c.choice_text }} --> {{ c.votes }} </li>
    {% endfor %}
</ul>
<hr>
<a href="{% url 'polls:home'%}">Inicio</a>

<div style="height: 400px; width: 600px;">
    <canvas id="myChart"></canvas>
</div>

<script>
    var labels = {{ labels|safe }};
    var data = {{ data|safe }};
    var ctx = document.getElementById('myChart').getContext('2d');
    var myChart = new Chart(ctx, {
        type: 'pie',
        data: {
            labels: labels,
            datasets: [{
                label: 'Votos',
                data: data,
                backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(54, 162, 235, 0.2)',
                    'rgba(255, 206, 86, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)'
                ],
                borderColor: [
                    'rgba(255, 99, 132, 1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)'
                ],
                borderWidth: 1
            }]
        },
        options: {
            title: {
                display: true,
                text: 'Resultados de la votación'
            },
            
            aspectRatio: 1
        }
    });
</script>

{% endblock %}